name: Add File to Bucket
on: push

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@main
   
    - name: Upload file to bucket
      uses: zacfrulloni/cloudresumechallenge-FrontEnd/index.html/s3-upload-github-action@main
      with:
       args: --acl public-read
    env:
     FILE: index.html
     AWS_REGION: 'eu-west-2'
     S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
