name: Upload to S3

on: [pull_request]

jobs:
  upload:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: shallwefootball/s3-upload-action@main
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'index.hmtl'
