name: Python package

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-west-2

    - name: S3 Deploy
      uses: Reggionick/s3-deploy@v3.1.0
      with:
         folder: C:\Users\zacfr\OneDrive\Desktop\visitor-counter (1)\visitor-counter\dist
         bucket: zacsresume.com
         bucket-region: eu-west-2
         dist-id: E3L31PEXV3KQZH
         invalidation: I2GSTZIXAG5JJX
     
     
