name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - uses: jakejarvis/s3-sync-action@main
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'zacsresume.com'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2'
